# Generated by Django 4.2.1 on 2023-06-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0002_alter_product_categories"),
        ("cart", "0002_remove_cart_purchased_cart_checkout"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(max_length=200)),
                ("province", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("shipping_address", models.CharField(max_length=200)),
                ("billing_address", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=200)),
                ("payment", models.CharField(max_length=200)),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cart.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
