# Generated by Django 4.2.1 on 2023-06-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="purchased",
        ),
        migrations.AddField(
            model_name="cart",
            name="checkout",
            field=models.CharField(
                choices=[("FALSE", "False"), ("TRUE", "True")],
                default="FALSE",
                max_length=5,
            ),
        ),
    ]
